# Generated by Django 4.2.2 on 2023-06-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tblog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='titulo_tag',
            field=models.CharField(default='blog viajes', max_length=255),
        ),
    ]
