# Generated by Django 4.2.2 on 2023-06-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tblog_app', '0006_alter_articulo_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen_header',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
