# Generated by Django 4.2.2 on 2023-06-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tblog_app', '0008_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/perfil/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sitio_web',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
